<?php

$itemsData = "CAN COKE	STORE	PCS	30
CAN FANTA	STORE	PCS	15
CAN SCHWEPPES	STORE	PCS	30
CAN SPRITE	STORE	PCS	6
GRANULATED SUGAR	STORE	GRAM	0
10 INCHES CAKE BOARD	STORE	PCS	20
10 INCHES CAKE PAN	STORE	PCS	0
12 INCHES CAKE BOARD	STORE	PCS	0
8 INCHES CAKE BOX LOW(UNBRD)	STORE	PCS	0
12 INCHES CAKE BOX	STORE	PCS	0
14 INCHES CAKE BOARD	STORE	PCS	0
14 INCHES CAKE BOX	STORE	PCS	0
16 INCHES CAKE BOARD	STORE	PCS	0
2 DOORS DEEP FREEZER	STORE	PCS	1
20 INCHES CAKE BOARD	STORE	PCS	0
22 INCHES CAKE BOARD	STORE	PCS	0
24 INCHES CAKE BOARD	STORE	PCS	0
3DOORS DEEP FREEZER	STORE	PCS	1
4 DOORS REFRIGERATOR	STORE	PCS	0
4TH STREET RED WINE	STORE	PCS	0
8 INCHES CAKE BOARD	STORE	PCS	3
A-4 PAPER	STORE	PK	1
ACRYLIC STAND	STORE	PCS	0
AIR FRESHNER	STORE	BTLS	5
ALMOND FLOUR	STORE	GRAM	3174
ALUMINIUM NON STICK MILK POT	STORE	PCS	0
AMARENA BLACKCHERRY	STORE	GRAM	21000
AMARENA BLACKCHERRY TOPPING (N01)	STORE	GRAM	40000
AMARENA SUPER FRUTTA BLACKCHERRY (E90)	STORE	GRAM	0
AMARENA TOPPING (I09)	STORE	GRAM	26000
ANANAS 500 CP	STORE	GRAM	0
APPLE FRUIT	STORE	GRAM	0
APPLE POWDER (L25)	STORE	GRAM	36000
ARACHIDI PEANUT	STORE	GRAM	0
AVOCADO PEAR	STORE	PCS	0
BACON	STORE	GRAM	0
BAGUETTE TRAY	STORE	PCS	0
BAILEYS	STORE	GRAM	0
BAKED BEANS	STORE	GRAM	4980
BAKED BEANS IN TOMATO SAUCE	STORE	GRAM	0
GREASE PROOF (PARCHMENT PAPER)	STORE	PKS	0
BAKING POWDER	STORE	GRAM	1362
BAKING SODA	STORE	GRAM	1500
BAMBOO LANTERN	STORE	PCS	0
BAMBOO SKEWER (100PCS)	STORE	PKS	4
BAMBOO SKEWER (BBQ STCK)	STORE	PKS	0
BANANA BREAD NYLON	STORE	PKS	0
BANANA BREAD PACK	STORE	PKS	0
BANANA FRUIT	STORE	GRAM	0
BARBECUE SAUCE	STORE	GRAM	820
BARCADI WHITE RUM	STORE	GRAM	3750
BARRISTA CARAMEL	STORE	GRAM	0
BASE ALBA	STORE	GRAM	0
BASE PAN	STORE	GRAM	0
BASIL LEAF	STORE	GRAM	0
BEEF FILLET	STORE	GRAM	0
BELL PEPPER	STORE	GRAM	0
BENTO BOX	STORE	PCS	0
BIG ICE CREAM CUP	STORE	PCS	0
BIG TORTILLA BREAD	STORE	PCS	0
CONSTANT COMMENT TEA	STORE	PCS	0
EARL GREY TEA	STORE	PCS	0
GINGER PEACH TUMERIC TEA	STORE	PCS	0
GREEN AND GINGER TEA	STORE	PCS	0
CLASSIC GREEN TEA	STORE	PCS	0
GREEN TEA DECAFFEINATED TEA	STORE	PCS	0
I LOVE LEMON TEA	STORE	PCS	0
LAVENDAR CHAMOMILE TEA	STORE	PCS	0
LEMON AND GINGER TEA	STORE	PCS	0
BIN BAG	STORE	PCS	160
BIRTHDAY TOPPER	STORE	PCS	0
BISCOFF SPREAD	STORE	PCS	0
BISCOTTO BISCUIT (E49)	STORE	PCS	18000
BLACK PEPPER POWDER	STORE	PCS	0
BLACK SEED PEPPER	STORE	PCS	0
BLACK STONELESS OLIVE OIL	STORE	PCS	0
BLUE BERRY	STORE	PCS	0
BLUE CHERRY JAM	STORE	PCS	0
BLUE CREAM (E13)	STORE	PCS	0
BLUE CURACOA	STORE	PCS	0
BLUE PEARL TOPPING	STORE	PCS	0
STRAWBERRY JAM	STORE	PCS	0
BOT PACK	STORE	PCS	0
BRANDED PAPER BAG	STORE	PCS	0
BRANDED POP CORN PACK	STORE	PCS	0
BRANDED SERVIETTE	STORE	PCS	24768
BRANDED SERVING TRAY	STORE	PCS	0
BRANDED SUGAR (BROWN)	STORE	GRAM	0
BRANDED SUGAR (WHITE)	STORE	GRAM	0
BRANDED TAKEOUT BAG BIG 	STORE	GRAM	0
BRANDED TAKEOUT PLASTIC CUP 	STORE	PK	0
BREAD IMPROVER	STORE	GRAM	0
BREAKABLE LONG BOWL	STORE	PCS	0
BROCCOLI	STORE	GRAM	0
BROWN SUGAR	STORE	GRAM	3000
BUBBLE GUM (E67)	STORE	GRAM	21000
BUBBLE GUM PASTA (i52)	STORE	GRAM	0
BUBBLE GUM SAUCE	STORE	GRAM	0
BURGER BOX	STORE	GRAM	0
BURGER SLICES	STORE	GRAM	0
CABBAGE	STORE	GRAM	0
CAJUN SPICE SEASONING	STORE	GRAM	0
CAKE CANDLE	STORE	PCS	0
CAKE PAPER CUP	STORE	PCS	0
CAKE CUPS BY 6	STORE	PCS	0
CAKE DUMMY  SET	STORE	PCS	0
CAKE PACK	STORE	PCS	3000
CAKE WRAP	STORE	PCS	0
CALYPSO	STORE	GRAM	0
CAN MALT	STORE	PCS	0
CAN SCHWEEPES TONIC	STORE	PCS	0
CAPUCCINO CUP	STORE	PCS	0
CARAMEL CREAM	STORE	GRAM	0
CARAMEL SAUCE	STORE	GRAM	0
CARAMEL SPREAD	STORE	GRAM	0
CARAMEL FLAVOUR SYRUP	STORE	GRAM	0
CARNIVAL POP CANDY	STORE	GRAM	0
CARROT	STORE	GRAM	0
CAULIFLOWER	STORE	GRAM	0
CELERY	STORE	GRAM	0
PEACH PASSION TEA	STORE	PCS	0
MORNING THUNDER TEA	STORE	PCS	0
PEPPERMINT TEA	STORE	PCS	0
CELOTAPE	STORE	PCS	5
CERAMIC DIPPING SAUCE BOWL	STORE	PCS	0
CERAMIC FACE-LIKE CUP	STORE	PCS	0
CERAMIC KETCHUP DIP CUP	STORE	PCS	0
CERAMIC TEA POT FOR ORGANIC BREW	STORE	PCS	0
CHAPMAN JAR	STORE	PCS	0
CHECKERS CUSTARD	STORE	GRAM	0
CHEESE CAKE BASE	STORE	PCS	0
HAND GLOVE( RUBBER)	STORE	PCS	3600
CHIA SEED	STORE	GRAM	0
CHICKEN FILLET	STORE	GRAM	0
CHICKEN LAP	STORE	GRAM	0
CHICKEN WING	STORE	GRAM	0
CHILLY SPICE	STORE	GRAM	0
CHIPS FRYING BASKET	STORE	PCS	0
CHLOE WAFER ROLLS	STORE	PCS	0
CHOCO - BISCUIT (I52)	STORE	GRAM	0
CHOCO BISCUIT GRAINS (W02)	STORE	GRAM	0
CHOCOBISCOTTO (PASTA E74)	STORE	GRAM	18000
CHOCO-COCONUT PASTA (E75)	STORE	GRAM	12000
DARK CHOCOLATE BLOCK	STORE	GRAM	0
WHITE CHOCOLATE BLOCK	STORE	GRAM	0
CHOCOLATE MELTING MACHINE	STORE	PCS	2
CHOCOLATE SOFTGEL (F18)	STORE	GRAM	20000
CHOCOLATE STICK	STORE	GRAM	0
CHOCOLATE TOPPING (SAUCE)	STORE	GRAM	0
CHOCORUM PASTA (E10)	STORE	GRAM	0
CHOPPING BOARD	STORE	GRAM	0
CINNAMON POWDER	STORE	GRAM	0
CIOCUROM PASTA	STORE	GRAM	0
CLING FILM	STORE	PCS	65
CLOVE	STORE	PK	0
CMC	STORE	GRAM	0
COCCO 500CPU	STORE	GRAM	0
COCKROACH KILLER	STORE	PK	0
COCKTAIL GLASS CUP	STORE	PCS	0
COCOA POWDER	STORE	GRAM	0
COCONUT FRUIT	STORE	GRAM	0
COCONUT MILK	STORE	GRAM	0
OREO POWDER	STORE	GRAM	0
COFFEE 50 (E.07)	STORE	GRAM	0
COFFEE LIQUOR	STORE	GRAM	0
COFFEE STIRRER	STORE	PK	0
COLLINS GLASS CUP	STORE	PCS	0
COMMERCIAL HEALTH BLENDER	STORE	PCS	0
CONCENTRATED ROOM SPRAY	STORE	BTL	0
CONDENSED MILK	STORE	GRAM	0
COOKIES BLACK PASTA	STORE	GRAM	0
COOKIES FROM KITCHEN	STORE	GRAM	0
COOKIES THE ORIGINAL	STORE	GRAM	0
COOKING SPRAY	STORE	BTL	0
COPERTURA ALLA NOCCIOLA	STORE	GRAM	0
COPERTURA CARAMELO	STORE	GRAM	0
COPERTURA CHOCOLATE COATING (E12)	STORE	GRAM	0
COPERTURA STRACCIATELA	STORE	GRAM	0
CORIANDER POWDER	STORE	GRAM	0
CORN FLOUR	STORE	GRAM	0
CORN TORTILLA	STORE	GRAM	0
BRANDED CERAMIC FOOD PLATE	STORE	PCS	0
CORNER STORE MOUTH CLEANER	STORE	PCS	0
BRANDED SERVING TRAY (C/S)	STORE	PCS	0
TABLE MAT	STORE	PCS	0
TAMPER SEAL	STORE	PCS	0
BRANDED COFFEE CUP	STORE	PCS	0
CORRECTION PEN	STORE	PCS	0
COTTON CANDY CONE	STORE	PCS	0
CRAFT KNIFE	STORE	PCS	0
CREAM CHEESE	STORE	GRAM	0
CREME BRULEE (E85)	STORE	GRAM	0
CREME BRULLE PASTA	STORE	GRAM	0
CREME CACAO (E14)	STORE	GRAM	0
CRIC CROC BISCUIT	STORE	GRAM	0
CRISPY WAFFLE MACHINE	STORE	GRAM	0
CRISPY FRYING MIX	STORE	GRAM	0
CUCUMBER	STORE	GRAM	0
CUKY GRAINS	STORE	GRAM	0
CUMMING POWDER	STORE	GRAM	0
BRANDED CUP CAKE BOX	STORE	PCS	0
UNBRANDED CUP CAKE BOX	STORE	PCS	0
PAPERCUP SLEEVE	STORE	PCS	0
CURRY POWDER	STORE	GRAM	0
CUTTER EMBOSSER	STORE	PCS	0
C-WAY WATER	STORE	GRAM	0
COOKING CREAM	STORE	GRAM	0
DARK CHOCOLATE CHIP	STORE	GRAM	0
DARK SOY SAUCE	STORE	GRAM	0
DD FORCE	STORE	BTL	0
TUNA FISH	STORE	GRAM	5640
DEEP FREEZER	STORE	PCS	0
DESSERT CUP	STORE	PCS	0
DESSERT FORK	STORE	PK	0
DESSERT IRON SPOON	STORE	PCS	0
DETERGENT	STORE	GRAM	0
DIGESTIVE BISCUIT	STORE	GRAM	156
DIGESTIVE POWDER	STORE	GRAM	0
DIJON MUSTARD	STORE	GRAM	1020
PEPPERMINT	STORE	PCS	0
DISPLAY CABINET	STORE	PCS	0
DOLCE DE LATTE CONCENTRATO	STORE	GRAM	0
DOLCE DE LATTE	STORE	GRAM	0
DOLCE DE LECHE (PASTRY)	STORE	GRAM	0
DOLCE DI LATTE (E.60)	STORE	GRAM	0
DOUBLE DOOR FRIDGE	STORE	PCS	0
DOUBLE ESPRESSOR CERAMIC CUP	STORE	PCS	0
DOUGH CLOTHE	STORE	PCS	0
DOUNUT BOX (BRANDED)	STORE	PCS	0
DRIED MIXED FRUIT	STORE	GRAM	0
EDIBLE GOLD BEAD	STORE	PK	0
EDIBLE REJUVINATING SPIRIT	STORE	BTL	0
EDIBLE SILVER BEAD	STORE	PK	0
EGG	STORE	PCS	0
ELECTRIC DIFFUSER	STORE	PCS	0
EMMENTAL CHEESE	STORE	GRAM	0
LEMON&GRASS TEA	STORE	PCS	0
EROS TEA	STORE	PCS	0
FAMILY & FRIENDS RED DRY WINE	STORE	GRAM	0
FAMILY & FRIENDS ROSE SWEET WINE	STORE	GRAM	0
FINGER BATTERY	STORE	PCS	0
FIODIBOSCO	STORE	GRAM	0
FIODIFRAGOLA	STORE	GRAM	0
FIORDILAMPONE	STORE	GRAM	0
FISH BATTER MIX	STORE	GRAM	0
FISH SAUCE	STORE	GRAM	0
FISH SEASONING	STORE	GRAM	0
FLAKE ALMOND	STORE	GRAM	0
FLORA WIRE	STORE	PK	0
FLORY TAPE	STORE	PCS	0
FLOSSY SUGAR (CANDY COTTON)	STORE	GRAM	0
FLOUR & SUGAR BIN	STORE	PCS	0
FLY CATCHER	STORE	PCS	0
FOIL PAPER	STORE	PK	0
FOIL PLATE SMALL	STORE	PK	0
FOIL PLATE BIG 	STORE	PCS	0
FOOD MIXER MACHINE	STORE	PCS	0
STRAWBERRY TOPPING 	STORE	GRAM	0
FRAGOLA  500CP	STORE	GRAM	0
FRAGOLA STRAWBERRY FRAISE (F03)	STORE	GRAM	96000
FRAGOLA STRAWBERRY FRAISE (L22)	STORE	GRAM	38400
FRAGOLA STRAWBERRY FRAISE VARIEGATURA(I11)	STORE	GRAM	0
FRAISE BARDINET	STORE	GRAM	0
FRENCH FRIES	STORE	GRAM	50000
FRENCH FRIES PACK 	STORE	GRAM	0
FRESH PEPPER	STORE	GRAM	0
FRESH TOMATOES	STORE	GRAM	0
FROST MILK JUG	STORE	PCS	0
FROZEN YOGHURT	STORE	GRAM	33000
FRUIT COCKTAIL	STORE	GRAM	330000
FRUIT JUICE GLASS	STORE	PCS	0
FRUITTI DI BOSCO	STORE	GRAM	7000
FUNKY MALTY	STORE	GRAM	0
GABLE BOX	STORE	PCS	0
GARLIC	STORE	GRAM	0
GARLIC POWDER	STORE	GRAM	0
GAS BURNER MACHINE	STORE	PCS	0
GAS GRIDDLE (FLAT PLATE) MACHINE	STORE	PCS	0
GAS PIZZA OVEN	STORE	PCS	0
GAS RANGE WITH 4 BURNER WITH GAS OVEN	STORE	PCS	0
GELATINE LEAF	STORE	GRAM	0
GELATINE POWDER	STORE	GRAM	0
GELATO CUP BRUSH	STORE	PCS	0
GELATO JUG	STORE	PCS	0
GINGER	STORE	GRAM	0
GINGER POWDER	STORE	GRAM	0
GINGER, ONION, GARLIC SEASONING	STORE	GRAM	0
GLAZE CARAMEL	STORE	GRAM	0
GLUCOSE	STORE	GRAM	0
GOBLET GLASS	STORE	PCS	0
GOLD DUST	STORE	PK	0
GOLD LEAVE	STORE	PK	0
GOLD RUM	STORE	GRAM	0
GOLDEN SELLA PURE (BASMATI RICE)	STORE	GRAM	0
GORDONS GIN	STORE	GRAM	0
GOURMET BURGER	STORE	GRAM	328
GRAN GOURMENT	STORE	GRAM	0
GRANELLA CHEESE CAKE	STORE	GRAM	0
GRANELLA-CUKY GRAINS(W04)	STORE	GRAM	0
GREEK YOUGHURT	STORE	GRAM	0
GREEN TEA POWDER	STORE	PCS	0
GRENADINE	STORE	GRAM	0
GROUNDNUT	STORE	GRAM	0
GUELLA PEANUT	STORE	GRAM	0
GUELLA RUBY	STORE	GRAM	12000
GUMMY BEAR	STORE	GRAM	0
GUN LIGHTER	STORE	PCS	1
CAMOMILE TEA	STORE	PCS	0
CAMOMILE & MANUKA HONEY TEA	STORE	PCS	0
MATCHA GREEN TEA	STORE	GRAM	0
NIGHT TIME TEA	STORE	PCS	0
HAIR NET	STORE	PK	0
ENGLISH BREAKFAST TEA	STORE	PCS	0
GREEN TEA & MINT TEA	STORE	PCS	0
PEPPERMINT & SPEARMINT TEA	STORE	PCS	0
ROOLBOS TEA	STORE	PCS	0
TUMERIC & CINNAMON TEA	STORE	PCS	0
HAND GLOVE (NYLON)	STORE	PK	86
HAND SANITIZER	STORE	BTL	0
HAND TOWEL	STORE	PCS	0
HARPIC	STORE	BTL	0
HAZELNUT FLAVOUR SYRUP	STORE	GRAM	0
HAZELNUT GRAINS	STORE	GRAM	12000
MILK COATED CHOCOLATE BALLS	STORE	GRAM	0
HAZELNUT SPREAD	STORE	GRAM	0
HAZELNUT TOPPING	STORE	GRAM	0
HINCHES	STORE	PCS	0
HOT CHOCOLATE	STORE	GRAM	1350
HOT PEPPER POWDER	STORE	GRAM	0
HYPO 	STORE	BTL	0
ICE BLOCK NYLON	STORE	PK	0
ICE CREAM PAN WITH COMPRESSOR	STORE	PCS	0
ICE CREAM SOFTSERVE MACHINE	STORE	PCS	0
ICE SPOON	STORE	PCS	0
ICE TEA RAPBERRY FLAVOURED TIN	STORE	PCS	0
ICING COLOUR	STORE	BTL	0
ICING SUGAR	STORE	GRAM	0
COFFEE BEAN CAFFEINATED	STORE	GRAM	0
COFFEE BEAN DECAF	STORE	GRAM	0
IMPULSE SEALER	STORE	PCS	0
IRISH COFFEE PASTE	STORE	GRAM	7000
IRISH POTATO	STORE	GRAM	0
IRON ICE COMB	STORE	PCS	0
IRON SPONGE	STORE	PCS	9
KETCHUP DIPS	STORE	PK	0
KETCHUP TOMATOE SACHET	STORE	PK	0
SILVER KNIFE (CUTLERY)	STORE	PCS	0
SILVER SPOON (CUTLERY)	STORE	PCS	0
KIT COOKIES BLACK	STORE	GRAM	0
KIT GUSTO MASHMELLOW	STORE	GRAM	0
KIT MAMA QUE BUENA	STORE	GRAM	0
KIT MECRAPH	STORE	GRAM	0
KIT MISTER NICO	STORE	GRAM	0
KIT UNICORN	STORE	GRAM	0
KIT UNICORN (NEW)	STORE	GRAM	0
KIT WHISKY CREAM	STORE	GRAM	0
KITCHEN KNIFE	STORE	GRAM	0
KIWI TOPPING 	STORE	GRAM	16000
LA PAZ RED-WINE	STORE	GRAM	0
LAMPONE RASPBERRY	STORE	GRAM	0
LATTE GLASS (WITH HANDLE)	STORE	PCS	0
LEATHER MART	STORE	GRAM	0
LEEK LEAF	STORE	GRAM	0
LEMON	STORE	GRAM	0
LETTUCE	STORE	GRAM	0
LIGHT SOY SAUCE	STORE	GRAM	0
LIMOCINO	STORE	GRAM	0
LIPTON ICED TEA	STORE	GRAM	0
LIQUID SOAP	STORE	GRAM	0
LOTUS BISCOF	STORE	GRAM	0
LOTUS BISCUIT CRUMBLES	STORE	GRAM	0
LUNCH PACK	STORE	PCS	0
M&SPECKLED EGG	STORE	PK	0
MACARON MIX	STORE	GRAM	0
MACARONI	STORE	GRAM	0
MACRON BOX	STORE	GRAM	0
MANDARINE (L20)	STORE	GRAM	18000
MAPLE SYRUP	STORE	GRAM	0
MARCARPONE 50	STORE	GRAM	0
MARCO POLO TEA	STORE	PCS	0
MARGARINE BUTTER (PASTRY)	STORE	GRAM	0
MARKER PEN	STORE	PCS	0
MARPLE SYRUP	STORE	GRAM	0
MASHMELLOW	STORE	GRAM	0
MASKING TAPE	STORE	GRAM	0
MATCHA POWDER	STORE	GRAM	0
MAYONNAISE	STORE	GRAM	8000
MEASURING SCALE	STORE	MECROCK PLUS	STORE	GRAM	0
GRAM	0
MEDIUM ICE CREAM CUP	STORE	PCS	0
MENTHE (E.28)	STORE	GRAM	0
MENTHE SYRUP	STORE	GRAM	0
MICKEY MOUSE WAFER MAKER	STORE	PCS	0
MICRO WAVE MACHINE	STORE	PCS	0
MICROWAVE OVEN SAFE	STORE	PCS	0
MILK CHOCOLATE BLOCK	STORE	GRAM	0
MILK SHAKE GLASS CUP	STORE	PCS	0
MINI BUTTER	STORE	PCS	0
MINT LEAVE	STORE	GRAM	0
MIX TO DRINK BLACK CURRANT	STORE	GRAM	0
GOLD SPRINKLE	STORE	PK	0
 SILVER SPRINKLE	STORE	PK	0
MODELING TOOLS	STORE	PCS	0
MOZZARELLA CHEESE	STORE	GRAM	0
MUSHROOM	STORE	GRAM	0
MULTI-FUNCTION FILM SEALING MACHINE	STORE	PCS	0
NERO NERO BLACK	STORE	GRAM	0
NESTLE WATER	STORE	PCS	0
NOCCIOFLAKES	STORE	GRAM	0
NOCCIOLATA PASTA (E.57)	STORE	GRAM	18000
NOSE MASK	STORE	PCS	0
NOTE BOOK	STORE	PCS	1
NUTELLA	STORE	GRAM	0
OFFICE DIFFUCER	STORE	PCS	0
OFFICE DIFFUCER FRAGRANCE	STORE	BTL	0
OFFICE FLAT FILE	STORE	PCS	11
OLIVE OIL	STORE	GRAM	1000
ONION POWDER	STORE	GRAM	0
ONIONS	STORE	GRAM	0
ORANGE	STORE	PCS	0
ORANGE JUICE 	STORE	GRAM	6000
OREGANO	STORE	GRAM	0
OREOS	STORE	GRAM	0
ORGANIC BREW TEA POT WARMER	STORE	PCS	0
OVEN GLOVE	STORE	PCS	0
PADLOCK	STORE	PCS	0
PANKO BREAD CRUMBS	STORE	GRAM	0
PANNA COTTA FLAVOURING PASTE (E69)	STORE	GRAM	0
PAPER CUP (UNBRANDED)	STORE	GRAM	0
PAPER SLEEVES FOR COFFEE CUP	STORE	PCS	0
PAPER STRAW	STORE	GRAM	0
PAPRIKA	STORE	GRAM	0
PAPRIKA POWDER	STORE	GRAM	0
PARLET KNIFE	STORE	PCS	0
PARMESSAN CHEESE	STORE	GRAM	0
PARSLEY LEAF	STORE	GRAM	0
PASTA AZZURRO CIELO	STORE	GRAM	0
PASTA & SALAD CERAMIC BOWL	STORE	PCS	0
PASTA BISCOTTINO	STORE	GRAM	0
PASTA CAFFEE CONCENTRATA	STORE	GRAM	0
PASTA CARAMEL	STORE	GRAM	0
PASTA CREMA CACAO	STORE	GRAM	0
PASTA FRENCH VANILLA	STORE	GRAM	0
PASTA FRUITTI BOSCO	STORE	GRAM	0
PASTA GAS COOKER WITH CABINET	STORE	PCS	0
PASTA MALAGA	STORE	GRAM	0
PASTA PISTACHIO SELECTION	STORE	GRAM	0
PASTA SCROK	STORE	GRAM	0
PASTA VANIGLIA DELICIOUS	STORE	GRAM	0
PASTA VANIGLIA REGINA	STORE	GRAM	0
PASTA VANILLA BOURBON	STORE	GRAM	0
PASTA VANILLA DELICIOUS	STORE	GRAM	0
PASTA WAFERS	STORE	GRAM	0
PASTRY BRUSH	STORE	GRAM	0
PANNA COTTA PASTA	STORE	GRAM	0
PEACH MELOCOTO (L28)	STORE	GRAM	0
PEACH SCHNAPPS	STORE	GRAM	0
PEAK MILK	STORE	GRAM	1529
PEN	STORE	PCS	0
PENNE PASTA	STORE	GRAM	0
PEONY BLOSSOM ROOM FRAGRANCE	STORE	BTL	0
PESCA CP 500	STORE	GRAM	0
PICKER	STORE	PCS	0
PICKLES	STORE	PK	0
PINEAPPLE FRUIT	STORE	GRAM	0
PINEAPPLE GLASS	STORE	PCS	0
PINEAPPLE JUICE	STORE	GRAM	5000
PINK SALT	STORE	GRAM	0
PISTACHIO CREAM	STORE	GRAM	0
PISTACHIO SYRUP	STORE	GRAM	0
PIZZA BOX	STORE	PCS	0
PLASTIC BUCKET FOR KITCHEN	STORE	PCS	0
PLASTIC COKE	STORE	GRAM	3500
PLASTIC DISPOSABLE TRAY	STORE	PCS	0
PLASTIC FANTA	STORE	GRAM	5000
PLASTIC FORK	STORE	PKS	1
PLASTIC FUNNEL	STORE	PCS	1
PLASTIC JAR	STORE	PCS	0
PLASTIC JARDS	STORE	PCS	0
PLASTIC RACK	STORE	PCS	0
PLASTIC SALAD BOWL	STORE	PCS	0
PLASTIC SPRITE	STORE	GRAM	2000
PLASTIC STRAW	STORE	PK	0
PLASTIC TAKEAWAY PLATE	STORE	PCS	0
PLASTIC TEEM SODA	STORE	GRAM	6500
POP CORN PACK (UNBRANDED)	STORE	PCS	0
POP CORN PACK (BRANDED)	STORE	PCS	0
POWDERED MILK	STORE	GRAM	0
PRAWN	STORE	GRAM	0
PROCELAIN CERAMIC CUP	STORE	PCS	0
PU-ERH ORGANIC MINT TEA	STORE	PCS	0
PUFF PASTRY MARGARINE	STORE	PCS	0
PUKKA THREE GINGER TEA	STORE	PCS	20
PURE HONEY	STORE	GRAM	0
RAW CORN	STORE	GRAM	0
RAZOR BLADE	STORE	PCS	0
REAL BALSAMIC VINEGAR	STORE	GRAM	0
REAL CHILLI SAUCE	STORE	GRAM	2100
RECELLERI MIXED FRUIT	STORE	GRAM	0
RED CHERRY FRUIT	STORE	GRAM	0
RED CHILLI POWDER	STORE	GRAM	300
RED COOKING WINE	STORE	GRAM	0
RED GRAPE	STORE	GRAM	0
RED SUGAR FLAIR	STORE	GRAM	0
RED VELVET POWDER	STORE	GRAM	80
RIBBON	STORE	PCS	0
ROLLING PIN	STORE	PCS	0
RUBBER BAND	STORE	PK	0
RUBICONE	STORE	GRAM	159500
SALAD CREAM	STORE	GRAM	1750
SALT	STORE	GRAM	0
SALTED BUTTER CARAMEL	STORE	GRAM	0
SALTY CARAMEL CREME	STORE	GRAM	0
SANADUE	STORE	GRAM	50000
SANTA PHONE	STORE	PCS	0
SANTANA NYLON	STORE	PK	0
SAPPERETE KIWI SYRUP	STORE	GRAM	3750
SAUSAGE	STORE	GRAM	0
SCISSORS	STORE	PCS	2
SCRUBBING BRUSH	STORE	PCS	0
SEMOLINA	STORE	GRAM	0
SERVIETTE	STORE	PK	0
SESAME OIL	STORE	GRAM	0
SESAME SEED	STORE	GRAM	0
SHORT GLASS CUP	STORE	PCS	0
SHORT GLASS TUMBLER	STORE	PCS	0
SHORT SPARKLING CANDLES	STORE	PCS	0
SHOT GLASS CUP	STORE	PCS	0
SHRIMP	STORE	GRAM	0
SINGLE CUP CAKE BOX	STORE	PCS	0
SLICE CAKE BOARD	STORE	PCS	0
SLICE CHEESE	STORE	GRAM	0
SMACK FLAVOURING (E36)	STORE	GRAM	24000
SMALL ICE CREAM CUP	STORE	PCS	0
SMALL KITCHEN OVEN	STORE	PCS	0
SMALL OVEN	STORE	PCS	0
SNACK PACK	STORE	PCS	0
SOAP DISPENCER	STORE	PCS	4
SOFT(NET) SPONGE	STORE	PCS	0
SOSA CERAMIC PLATE	STORE	PCS	0
SPAGHETI	STORE	GRAM	0
SPATULA	STORE	PCS	0
SPEKULOOS	STORE	GRAM	0
SPINACH	STORE	GRAM	0
SPRING ONIONS	STORE	GRAM	0
SPRINKLES	STORE	PK	0
SQUEEZE DISHER	STORE	PCS	0
STAB HAZELNUT (E35)	STORE	GRAM	12000
STACKING BOARD	STORE	PCS	0
STAFF WATER	STORE	BAGS	0
STAINLESS BOWL	STORE	PCS	0
STALK SMOOTHER BOARD	STORE	PCS	0
STAND MIXER	STORE	PCS	0
STANDS FOR OUTDOOR SERVICE	STORE	PCS	0
STAPLING PIN	STORE	PK	0
STEAKBURGER SEASONING	STORE	GRAM	0
STENCIL	STORE	PCS	0
STRAWBERRY FOR (SOFTSERVE)	STORE	GRAM	0
STRAWBERRY MANTYGEL	STORE	GRAM	0
SUMNACON (HONEY) GLASS	STORE	PCS	0
SUPER GLUE	STORE	PCS	4
SUYA SPICE	STORE	PK	1
SWEEPING BROOM (NATIVE)	STORE	PCS	0
SWEEPING BRUSH	STORE	PCS	0
SWEET CORN	STORE	GRAM	0
BRANDED NYLON	STORE	PK	0
BRANDED TRAY	STORE	PCS	0
SWEETTOOTH WAFER	STORE	PCS	0
TABLE FLOWER	STORE	PCS	0
TAPIOCA PEARLS	STORE	GRAM	0
TEA GLASS CUP	STORE	PCS	0
TEA SPOON	STORE	PCS	0
TEQUILA	STORE	GRAM	0
TESTER SPOON	STORE	PK	0
THERMAL PAPER	STORE	PCS	0
THYME LEAVE	STORE	GRAM	0
TIRAMISU PASTA (E.55)	STORE	GRAM	18000
TISSUE	STORE	PCS	0
TOMATO KETCHUP	STORE	GRAM	0
TOMATO PASTE	STORE	GRAM	0
TOMATO SACHET KETCHUP	STORE	PCS	0
TOOTHPICK	STORE	PK	0
TOP GUM	STORE	BTL	0
TOWEL WARMER	STORE	PCS	0
TRAY FOIL PLATE	STORE	PCS	0
TRIPLE SEC LIQUOR	STORE	GRAM	0
TRIPOD STAND	STORE	PCS	0
TUMERIC POWDER	STORE	GRAM	0
TURNING STICK	STORE	PCS	0
TWINE ROPE	STORE	PCS	0
CHAI TEA	STORE	PCS	0
PURE GREEN TEA	STORE	PCS	0
ORANGE, MANGO & CINNAMON TEA	STORE	PCS	0
TWIST NYLON TIE	STORE	PCS	0
UHT MILK	STORE	GRAM	0
UMBRELLA	STORE	PCS	0
UNSALTED BUTTER	STORE	GRAM	0
URINAL BLOCK	STORE	PCS	0
VAMOLA (LIQUID)	STORE	GRAM	0
VAMOLA WHITE BIANCO (I93)	STORE	GRAM	0
VANILLA  50 (FLAVOURING PASTE) - E40	STORE	GRAM	0
VANILLA  GELATO(F02)	STORE	GRAM	99000
VANILLA AS (F17) SOFTSEWRVE	STORE	GRAM	180000
VANILLA EXTRACT	STORE	GRAM	1000
VANILLA FLAVOUR SYRUP	STORE	GRAM	0
VANILLA WHISKY CREAM	STORE	GRAM	0
VARIEGATO AMARENA BLACKBERRY	STORE	GRAM	0
VARIEGATO CHOCOBISCOTTO	STORE	GRAM	0
VARIEGATO DOLCE DI LATTE	STORE	GRAM	0
VARIEGATO HONEY COMB	STORE	GRAM	0
VARIEGATO NOCCIOLATA (I55)	STORE	GRAM	0
VARIEGATO PER CREME BRULEE	STORE	GRAM	0
VARIEGATO TIRAMISU	STORE	GRAM	0
VARIEGATO WAFERS	STORE	GRAM	0
VEGETABLE CUTTER MACHINE	STORE	PCS	0
VEGETABLE FAT	STORE	GRAM	0
VEGETABLE OIL	STORE	GRAM	0
VEGETABLE PEELER	STORE	PCS	0
VIM	STORE	PK	0
VODKA	STORE	GRAM	0
WAFER ROLLS	STORE	PCS	0
WAFFLE CONE MACHINE	STORE	PCS	0
WAFFLE CONE SLEEVES	STORE	PCS	0
WAFLE BAKER MACHINE	STORE	PCS	0
WALNUT	STORE	GRAM	0
WASTE BIN BUCKET	STORE	PCS	0
WATER GLASS CUP	STORE	PCS	0
WATER GLASS LONG (400ML)	STORE	PCS	0
WATER GLASS SHORT (200ML)	STORE	PCS	0
WATER PUSHER	STORE	PCS	0
WHIPPING CREAM	STORE	GRAM	0
WHISKY PASTE	STORE	GRAM	0
WHITE CHOCOLATE PASTA (E59)	STORE	GRAM	0
WHITE CHOCOLATE CHIP	STORE	GRAM	0
WHITE FISH FILLET	STORE	GRAM	0
WHITE FLOUR	STORE	GRAM	0
WHITE ONIONS	STORE	GRAM	0
WHITE PEARLS	STORE	GRAM	0
WHITE PEPPER POWDER	STORE	GRAM	0
WHITE RUM	STORE	GRAM	0
WHITE VINEGAR	STORE	GRAM	0
WHITE WINE	STORE	GRAM	0
WILDBERRIES (E.72)	STORE	GRAM	0
WINE GLASS	STORE	PCS	0
WIPE	STORE	PCS	0
WOODEN DOWEL ROD	STORE	PK	0
WOODEN FORK	STORE	PK	0
WOODEN ROLLER	STORE	PCS	0
YEAST	STORE	GRAM	0
YOGI POSITIVE ENERGY	STORE	PCS	0
ZIP LOC (BIG)	STORE	PCS	0
ZIPLOC (SMALL)	STORE	PCS	0
ZOBO LEAVE	STORE	GRAM	0
GREEN TEA WITH POMEGRANATE TEA	STORE	PCS	0
LAVENDER CHAMOMILE TEA	STORE	PCS	0
OAK MILK	STORE	GRAM	2838
ORGANIC PU-ERH TEA WITH CHOCOLATE	STORE	PCS	0
PEANUT TOPPING GELATO	STORE	PCS	0
POWER HORSE	STORE	PCS	14
RASPBERRY ICED TEA	STORE	GRAM	4409
SHORT SPARKLING CANDLE	STORE	PCS	0
VARIEGATO IMAMA QUE BUENA	STORE	GRAM	0
QUELLA PEANUT	STORE	GRAM	0
PASTA IMAMA QUE BUENA	STORE	GRAM	0
WHEAT FLOUR	STORE	GRAM	0
CIOCCOMANIA	STORE	GRAM	0
STRAWBERRY FRUIT	STORE	GRAM	0
TATASHE	STORE	GRAM	0
ALMOND MILK	STORE	GRAM	2838
CHOCOLATE COATING SAUCE	STORE	GRAM	0
HIBISCUS TEA	STORE	PCS	0
OREOS CRUSH	STORE	GRAM	0
PASTA TIRAMISU	STORE	GRAM	0
ORANGE JUICE	STORE	GRAM	6000
POS PAPER	STORE	PCS	134
PIPPING BAG	STORE	PCS	0
KNOR MAGGI (BEEF & CHICKEN)	STORE	GRAM	3600
TABLE TOP MIXER	STORE	PCS	0
WOODEN SPOON	STORE	PK	0
FOAM SPONGE	STORE	PCS	0
SWEET CHILLI SAUCE	STORE	GRAM	0
BIRTHDAY CUTTER	STORE	PCS	0
ZIPLOC	STORE	PCS	0
PASTA MECRAPH	STORE	GRAM	0
BEEF STEAK	STORE	GRAM	0
DATES	STORE	GRAM	0
GOLDEN SYRUP	STORE	GRAM	0
MOPPING STICK	STORE	PCS	0
PLASTIC BASKET	STORE	PCS	0
CAKE NOZZLE	STORE	PCS	0
BREAD KNIVE	STORE	PCS	0
MOLASSE SYRUP	STORE	GRAM	0
FOOD SPOON	STORE	PCS	0
CERAMIC FLAT BOWL PLATE	STORE	PCS	0
RED SPOON POUCH	STORE	PCS	0
APRICOT JAM	STORE	GRAM	450
HAND WASH	STORE	BTL	4
GAZ BLOW TORCH	STORE	PCS	0
ROSEMARY SPICE	STORE	GRAM	0
MR CHEF SEASONING	STORE	GRAM	100
SILICON BRUSH	STORE	PCS	0
SILVE	STORE	PCS	0
18 INCHES CAKE BOARD	STORE	PCS	0
PASSION FRUIT PURÉE	STORE	GRAM	0
TOZO	STORE	GRAM	0
DRY PEPPER	STORE	GRAM	0
BREAD TOASTER 	STORE	GRAM	0
ALMOND SEED	STORE	GRAM	750
DOUGHNUT BOX	STORE	PCS	500
LED LIGHT	STORE	PCS	0
RASPBERRY ICED TEA 	STORE	GRAM	38069
FOREIGN LEMON	STORE	GRAM	0
PEACH SYRUP	STORE	GRAM	0
LEMONADE	STORE	GRAM	0
STEAK N CHOP	STORE	GRAM	0
BOLD SMOKY	STORE	GRAM	181
FIZZY TOPPING	STORE	GRAM	0
GUMMY WORM	STORE	GRAM	0
TWINING INFUSO	STORE	PCS	0
BLUEBERRY SLIM LIFE TEA	STORE	PCS	0
CONSTIPATION SUPPORT TEA	STORE	PCS	0
SUPPORT ANTIOXIDANT TEA	STORE	PCS	0
GINGER HONEY TEA	STORE	PCS	0
85 LITRES BOWL 	STORE	PCS	0
BREAD SOFTENER	STORE	GRAM	0
SQUADRON	STORE	GRAM	750
HOISIN SAUCE	STORE	GRAM	0
CORN FLAKES	STORE	GRAM	0
GRATER	STORE	PCS	0
LEMON MERIGUE	STORE	GRAM	0
YOGHIN	STORE	GRAM	0
SUPERGLEMIX	STORE	GRAM	0
PASTA ANANAS	STORE	GRAM	0
PRESERVATIVE	STORE	GRAM	0
MILK FLAVOUR	STORE	GRAM	0
EDC	STORE	GRAM	0
BAGUETTE BREAD PACK	STORE	PCS	500";

$uomMap = [
    'GRAM' => 1,
    'PCS' => 7,
    'PK' => 15,
    'PKS' => 15,
    'BTL' => 17,
    'BTLS' => 17,
    'BAGS' => 19,
    'JAR' => 18,
];

$branch = \App\Models\Branch::first();
$branchId = $branch->id;

$itemsUpdated = 0;
$itemsCreated = 0;
$stockUpdated = 0;
$skipped = 0;

$lines = explode("\n", $itemsData);

foreach ($lines as $line) {
    $line = trim($line);
    if (empty($line)) continue;
    
    $parts = preg_split('/\t+/', $line);
    if (count($parts) < 3) continue;
    
    $name = strtoupper(trim($parts[0])); // Capitalize
    $location = trim($parts[1]);
    $measurement = trim($parts[2]);
    $stock = isset($parts[3]) ? trim($parts[3]) : '';
    
    // Default stock to 0 if blank
    $stockQty = ($stock === '' || $stock === null) ? 0 : (float) str_replace(',', '', $stock);
    
    $uomId = $uomMap[$measurement] ?? 7; // Default to PCS
    
    // Find item (case insensitive)
    $item = \App\Models\Item::whereRaw('UPPER(name) = ?', [$name])->first();
    
    if ($item) {
        // Item exists - update only stock, skip creating
        $itemsUpdated++;
        echo "UPDATED STOCK: $name -> $stockQty\n";
    } else {
        // Create new item
        $item = \App\Models\Item::create([
            'name' => $name,
            'sku' => \Illuminate\Support\Str::random(8),
            'category' => 'raw_material',
            'uom_id' => $uomId,
            'branch_id' => $branchId,
            'status' => 'active',
            'requires_request' => 1,
        ]);
        $itemsCreated++;
        echo "CREATED: $name\n";
    }
    
    // Always create/update stock
    $stockRec = \App\Models\Stock::where('item_id', $item->id)->first();
    if ($stockRec) {
        $stockRec->update(['quantity_available' => $stockQty]);
    } else {
        \App\Models\Stock::create([
            'branch_id' => $branchId,
            'item_id' => $item->id,
            'quantity_available' => $stockQty,
            'quantity_reserved' => 0,
            'quantity_damaged' => 0,
            'health_status' => 'good',
        ]);
    }
    $stockUpdated++;
}

echo "\n=== SUMMARY ===\n";
echo "Items Created: $itemsCreated\n";
echo "Items Stock Updated: $itemsUpdated\n";
echo "Stock Records Updated: $stockUpdated\n";
echo "Total processed: " . ($itemsCreated + $itemsUpdated) . "\n";
